# Release workflow copied from polars and adapted
# https://github.com/pola-rs/polars/blob/main/.github/workflows/release-python.yml

name: Release Python

on:
  push:
    tags:
      - py-*

env:
  RUST_TOOLCHAIN: nightly-2023-07-27
  PYTHON_VERSION: '3.8'
  MATURIN_VERSION: '1.1.0'
  MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}

defaults:
  run:
    shell: bash

jobs:
  manylinux-x64_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Fix README symlink
        run: |
          cp README.md fexpress-py/README.md

      - name: Publish wheel
        uses: messense/maturin-action@v1
        env:
          RUSTFLAGS: -C target-feature=+fxsr,+sse,+sse2,+sse3,+ssse3,+sse4.1,+sse4.2,+popcnt,+avx,+fma
        with:
          command: publish
          args: -m fexpress-py/Cargo.toml --skip-existing -o wheels -u __token__
          maturin-version: ${{ env.MATURIN_VERSION }}
          rust-toolchain: ${{ env.RUST_TOOLCHAIN }}

  # Needed for Docker on Apple M1
  manylinux-aarch64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # Needed to avoid out-of-memory error
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: Fix README symlink
        run: |
          cp README.md fexpress-py/README.md

      - name: Publish wheel
        uses: messense/maturin-action@v1
        env:
          JEMALLOC_SYS_WITH_LG_PAGE: 16
        with:
          command: publish
          args: -m fexpress-py/Cargo.toml --skip-existing --no-sdist -o wheels -i python -u __token__
          target: aarch64-unknown-linux-gnu
          maturin-version: ${{ env.MATURIN_VERSION }}
          rust-toolchain: ${{ env.RUST_TOOLCHAIN }}

  win-macos:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Fix README symlink
        run: |
          cp README.md fexpress-py/README.md

      - name: Publish wheel
        uses: messense/maturin-action@v1
        env:
          RUSTFLAGS: -C target-feature=+fxsr,+sse,+sse2,+sse3,+sse4.1,+sse4.2
        with:
          command: publish
          args: -m fexpress-py/Cargo.toml --no-sdist --skip-existing -o wheels -i python -u __token__
          maturin-version: ${{ env.MATURIN_VERSION }}
          rust-toolchain: ${{ env.RUST_TOOLCHAIN }}

  macos-aarch64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Fix README symlink
        run: |
          cp README.md fexpress-py/README.md

      - name: Set up Rust targets
        run: rustup target add aarch64-apple-darwin

      - name: Publish wheel
        uses: messense/maturin-action@v1
        with:
          command: publish
          args: -m fexpress-py/Cargo.toml --target aarch64-apple-darwin --no-sdist -o wheels -i python -u __token__
          maturin-version: ${{ env.MATURIN_VERSION }}